import type { MetadataRoute } from "next/server"
import { Press_Start_2P } from "next/font/google"

const pixelFont = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pixel",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${pixelFont.variable} font-pixel`}>{children}</body>
    </html>
  )
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
} satisfies MetadataRoute



import './globals.css'